leftnav:
- identifier: daced6d6-3ad2-d0f1-8f10-bf974c740fb5
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 4ac2547f-e6a9-d938-44cb-8b3e57bcea65
  name: Readings and Assignments
  pageRef: /pages/readings-and-assignments
  weight: 20
- identifier: 46782ca0-dfd9-e561-49f4-53bca12d9f77
  name: Exams
  pageRef: /pages/exams
  weight: 30
- identifier: 7d32f04d-2234-de64-3999-87c533226c9c
  name: Tools
  pageRef: /pages/tools
  weight: 40
